[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true  # Enable IR-based code generation
gas_reports = ["OAUToken", "OAUNameRegistry"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[profile.ci]
fuzz = { runs = 1000 }
verbosity = 4

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
sepolia = "${RPC_URL_TESTNET}"
base = "${RPC_URL_MAINNET}"
base_sepolia = "${RPC_URL_TESTNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
